steps:
# Install dependencies with pnpm
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'npm'
  args: ['install', '-g', 'pnpm']

- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'pnpm'
  args: ['install']

# Create a directory for sprites.chr if it doesn't exist
- name: 'gcr.io/cloud-builders/bash'
  entrypoint: 'bash'
  args: ['-c', 'mkdir -p src/asm']

# Copy sprites.chr if it exists (you'll need to add this file to your repo)
- name: 'gcr.io/cloud-builders/bash'
  entrypoint: 'bash'
  args: ['-c', 'if [ -f sprites.chr ]; then cp sprites.chr src/asm/; fi']

# Download NESASM if needed
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'pnpm'
  args: ['run', 'download-nesasm']

# Build the project
- name: 'gcr.io/cloud-builders/npm'
  entrypoint: 'pnpm'
  args: ['run', 'build']

# Deploy to Cloud Storage
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gsutil'
  args: ['-m', 'rsync', '-r', '-d', 'public', 'gs://nes.jakoblangtry.com']

# Set website metadata
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gsutil'
  args: ['web', 'set', '-m', 'index.html', '-e', '404.html', 'gs://nes.jakoblangtry.com']

# Make sure all files are publicly readable
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gsutil'
  args: ['-m', 'acl', 'ch', '-r', '-u', 'AllUsers:R', 'gs://nes.jakoblangtry.com']

# Set Cache-Control metadata
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gsutil'
  args: ['-m', 'setmeta', '-h', 'Cache-Control:public,max-age=3600', 'gs://nes.jakoblangtry.com/**']

timeout: 1800s 